<?php

namespace App\Exceptions;

use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Validation\ValidationException;
use Illuminate\Http\Response as HttpResponse;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array<int, class-string<Throwable>>
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        if ($e instanceof AuthenticationException) {
            return response()->json([
                'error' => true,
                'code' => HttpResponse::HTTP_UNAUTHORIZED,
                'message' => $e->getMessage(),
            ], HttpResponse::HTTP_UNAUTHORIZED);
        }

        if ($e instanceof AuthorizationException) {
            return response()->json([
                'error' => true,
                'code' => HttpResponse::HTTP_UNAUTHORIZED,
                'message' => $e->getMessage(),
            ], HttpResponse::HTTP_UNAUTHORIZED);
        }

        if ($e instanceof ModelNotFoundException) {
            return response()->json([
                'error' => true,
                'code' => HttpResponse::HTTP_NOT_FOUND,
                'message' => 'Data Not found'
            ], HttpResponse::HTTP_NOT_FOUND);
        }

        if ($e instanceof ValidationException) {
            return response()->json([
                'error' => true,
                'code' => HttpResponse::HTTP_UNPROCESSABLE_ENTITY,
                'message' => $e->getMessage(),
                'errors' => $e->errors()
            ], HttpResponse::HTTP_UNPROCESSABLE_ENTITY);
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
